// C08StartupProgressHook.idl : C08StartupProgressHook 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(C08StartupProgressHook.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(050E5076-74EE-47AE-948D-7E2F6D841D50),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IStarupProgressHook : IDispatch{
};
[
	uuid(E13E5C68-7E8F-41AE-B3E8-27FF6BAA1106),
	version(1.0),
]
library C08StartupProgressHookLib
{
	importlib("stdole2.tlb");
	[
		uuid(A0551CF4-63C6-4C1E-A419-41D2E6437BF6)		
	]
	coclass StarupProgressHook
	{
		[default] interface IStarupProgressHook;
	};
};

